version: '3.3'
services:

  mysql:
    image: mysql:${CAS_BUGZILLA_MYSQL_VER}
    container_name: bugzilla_mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'bugs'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'bugs'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'bugspsw'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '${CAS_BUGZILLA_MYSQL_PORT}:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - bugzilla_data:/var/lib/mysql
    networks:
      - bugzilla_net
    restart: always

  bugzilla:
    build:
      context: ./bugzilla
      args:
          - REPO_BRANCH=${CAS_BUGZILLA_RELEASE}
    image: cas.bugzilla:1.0
    container_name: bugzilla
    ports:
      - ${CAS_BUGZILLA_HTTP_PORT}:80
      - ${CAS_BUGZILLA_API_PORT}:5900
    networks:
      - bugzilla_net
    depends_on:
      - mysql
    restart: always

# Names our volume
volumes:
  bugzilla_data:

networks:
  bugzilla_net:
    driver: bridge
