version: "2"

services:

  db:
    build: db
    image: cas.mattermost_db:1.0
    container_name: mattermost_db
    read_only: true
    restart: always
    volumes:
      - mattermost_postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      # - ./volumes/db/var/lib/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${CAS_MATTERMOST_DB_USR}
      - POSTGRES_PASSWORD=${CAS_MATTERMOST_DB_PSW}
      - POSTGRES_DB=${CAS_MATTERMOST_DB_NAME}
    # uncomment the following to enable backup
    #  - AWS_ACCESS_KEY_ID=XXXX
    #  - AWS_SECRET_ACCESS_KEY=XXXX
    #  - WALE_S3_PREFIX=s3://BUCKET_NAME/PATH
    #  - AWS_REGION=us-east-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      args:
          - REPO_TAG=${CAS_MATTERMOST_RELEASE}
      #   - edition=team
      #   - PUID=1000
      #   - PGID=1000
    image: cas.mattermost_app:1.0
    container_name: mattermost_app
    restart: always
    volumes:
      - mattermost_conf:/mattermost/config:rw
      - mattermost_data:/mattermost/data:rw
      - mattermost_logs:/mattermost/logs:rw
      - mattermost_plugins:/mattermost/plugins:rw
      - mattermost_client_plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # - ./volumes/app/mattermost/config:/mattermost/config:rw
      # - ./volumes/app/mattermost/data:/mattermost/data:rw
      # - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      # - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      # - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      # - /etc/localtime:/etc/localtime:ro
    environment:
      # set same as db credentials and dbname
      - MM_USERNAME=${CAS_MATTERMOST_DB_USR}
      - MM_PASSWORD=${CAS_MATTERMOST_DB_PSW}
      - MM_DBNAME=${CAS_MATTERMOST_DB_NAME}
      - MM_SERVICESETTINGS_SITEURL=${CAS_MATTERMOST_SITEURL}
      # in case your config is not in default location
      #- MM_CONFIG=/mattermost/config/config.json

  web:
    build:
      context: ./web
    image: cas.mattermost_web:1.0
    container_name: mattermost_web
    ports:
      - "${CAS_MATTERMOST_HTTP_PORT}:80"
      - "${CAS_MATTERMOST_HTTPS_PORT}:443"
    read_only: true
    restart: always
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
    # Uncomment for SSL
    # environment:
    #  - MATTERMOST_ENABLE_SSL=true


volumes:
  mattermost_postgres_data:
  mattermost_conf:
  mattermost_data:
  mattermost_logs:
  mattermost_plugins:
  mattermost_client_plugins:
